name: PhyloProcessR
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - spades>=3.15.2
  - samtools=1.17
  - r-doparallel=1.0.17
  - r-ape=5.7_1
  - r-data.table=1.14.8
  - r-essentials=4.2
  - r-rdrop2=0.8.2.1
  - r-seqinr=4.2_30
  - r-stringr=1.5.0
  - r-foreach=1.5.2
  - r-biomartr=1.0.2
  - r-devtools=2.4.5
  - orna=2.0
  - cd-hit=4.8.1
  - bioconductor-rsamtools=2.14.0
  - blast>=2.12.0
  - mafft=7.520
  - trimal=1.4.1
  - bioconductor-genomicranges=1.50.0
  - bioconductor-biostrings=2.66.0
  - bioconductor-shortread=1.56.0
  - bwa=0.7.17
  - hisat2=2.2.1
  - gatk4=4.4.0.0
  - fastp=0.23.2
  - r-stringi=1.7.12
