name: PhyloCap
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconductor-biocfilecache=2.2.0
  - r-tidyselect=1.2.0
  - cairo=1.16.0
  - fonts-conda-ecosystem=1
  - r-snow=0.4_4
  - libnghttp2=1.47.0
  - r-kernsmooth=2.23_20
  - tzdata=2022d
  - r-r.oo=1.25.0
  - r-roxygen2=7.2.1
  - r-openssl=2.0.3
  - _libgcc_mutex=0.1
  - r-xml=3.99_0.11
  - r-shiny=1.7.2
  - xorg-renderproto=0.11.1
  - r-biomartr=1.0.2
  - r-xtable=1.8_4
  - libxml2=2.10.2
  - r-pkgbuild=1.3.1
  - r-blob=1.2.3
  - r-seqinr=4.2_16
  - r-htmltools=0.5.3
  - r-xopen=1.0.0
  - liblapack=3.9.0
  - r-rcpp=1.0.9
  - r-rcurl=1.98_1.9
  - r-assertive.matrices=0.0_2
  - trimal=1.4.1
  - r-bitops=1.0_7
  - r-ini=0.3.1
  - harfbuzz=5.3.0
  - xorg-inputproto=2.3.2
  - r-glue=1.6.2
  - jpeg=9e
  - r-rstudioapi=0.14
  - libffi=3.4.2
  - r-devtools=2.4.4
  - r-pkgconfig=2.0.3
  - r-brew=1.0_8
  - r-assertive.types=0.0_3
  - r-remotes=2.4.2
  - fontconfig=2.14.0
  - xorg-libxtst=1.2.3
  - perl-parent=0.236
  - lcms2=2.12
  - r-sys=3.4
  - libiconv=1.17
  - perl-encode=3.19
  - libcblas=3.9.0
  - xorg-libsm=1.2.3
  - pcre=8.45
  - r-memoise=2.0.1
  - r-commonmark=1.8.0
  - r-iterators=1.0.14
  - perl-compress-raw-bzip2=2.201
  - perl-io-zlib=1.14
  - gatk4=4.3.0.0
  - xorg-libxext=1.3.4
  - r-formatr=1.12
  - libgit2=1.3.0
  - r-assertive.data.uk=0.0_2
  - bioconductor-biobase=2.54.0
  - r-downloader=0.4
  - perl-common-sense=3.75
  - icu=70.1
  - r-ps=1.7.1
  - bzip2=1.0.8
  - xorg-kbproto=1.0.7
  - bioconductor-summarizedexperiment=1.24.0
  - r-assertive=0.3_6
  - r-magrittr=2.0.3
  - freetype=2.12.1
  - perl-archive-tar=2.40
  - mpi=1.0
  - bioconductor-bsgenome=1.62.0
  - r-curl=4.3.3
  - r-doparallel=1.0.17
  - r-miniui=0.1.1.1
  - r-assertive.files=0.0_2
  - iqtree=2.2.0.3
  - xorg-libxfixes=5.0.3
  - bioconductor-genomeinfodbdata=1.2.7
  - make=4.3
  - bioconductor-biocio=1.4.0
  - r-ellipsis=0.3.2
  - htslib=1.16
  - r-rlang=1.0.6
  - r-vroom=1.6.1
  - font-ttf-ubuntu=0.83
  - entrez-direct=16.2
  - r-rematch2=2.1.2
  - gsl=2.7
  - bioconductor-matrixgenerics=1.6.0
  - r-diffobj=0.3.5
  - r-bslib=0.4.0
  - r-prettyunits=1.1.1
  - r-tzdb=0.3.0
  - r-png=0.1_7
  - r-bit64=4.0.5
  - zlib=1.2.12
  - libwebp-base=1.2.4
  - fonts-conda-forge=1
  - r-sass=0.4.2
  - r-assertive.data=0.0_3
  - r-futile.logger=1.4.3
  - r-profvis=0.3.7
  - r-ragg=1.2.3
  - r-promises=1.2.0.1
  - r-fs=1.5.2
  - r-digest=0.6.29
  - zstd=1.5.2
  - r-tibble=3.1.8
  - r-assertive.datetimes=0.0_3
  - r-foreach=1.5.2
  - curl=7.85.0
  - bioconductor-keggrest=1.34.0
  - r-philentropy=0.7.0
  - r-r.methodss3=1.8.2
  - r-assertive.sets=0.0_3
  - r-r.utils=2.12.2
  - r-lattice=0.20_45
  - r-rcmdcheck=1.4.0
  - r-whisker=0.4
  - sqlite=3.39.2
  - r-matrixstats=0.62.0
  - r-matrix=1.5_1
  - beagle-lib=4.0.0
  - r-sp=1.5_0
  - r-filelock=1.0.2
  - r-assertive.code=0.0_3
  - r-gert=1.5.0
  - pip=22.2.2
  - r-futile.options=1.0.1
  - samtools=1.16.1
  - r-backports=1.4.1
  - xz=5.2.6
  - r-cpp11=0.4.2
  - perl-list-moreutils=0.430
  - r-assertthat=0.2.1
  - graphite2=1.3.13
  - r-lambda.r=1.2.4
  - fastp=0.23.2
  - bioconductor-xvector=0.34.0
  - hdf5=1.12.1
  - r-base64enc=0.1_3
  - r-rversions=2.1.2
  - openjdk=8.0.332
  - libcurl=7.85.0
  - r-praise=1.0.0
  - lerc=4.0.0
  - libzlib=1.2.12
  - r-usethis=2.1.6
  - r-purrr=0.3.5
  - giflib=5.2.1
  - libuuid=2.32.1
  - r-pkgload=1.3.0
  - xorg-libxau=1.0.9
  - xorg-xextproto=7.3.0
  - r-waldo=0.4.0
  - r-data.table=1.14.8
  - xorg-libxdmcp=1.1.3
  - r-dbi=1.1.3
  - _r-mutex=1.0.1
  - libtool=2.4.6
  - perl-io-compress=2.201
  - r-assertive.properties=0.0_5
  - r-tinytex=0.42
  - r-cli=3.4.1
  - perl-types-serialiser=1.01
  - r-hms=1.1.2
  - r-rprojroot=2.0.3
  - perl-json=4.10
  - xorg-fixesproto=5.0
  - libopenblas=0.3.21
  - r-rdrop2=0.8.2.1
  - gettext=0.19.8.1
  - r-utf8=1.2.2
  - perl-list-moreutils-xs=0.430
  - bioconductor-delayedarray=0.20.0
  - r-httr=1.4.4
  - r-xfun=0.33
  - r-bh=1.78.0_0
  - r-rappdirs=0.3.3
  - libtiff=4.4.0
  - r-pixmap=0.4_12
  - mafft=7.515
  - perl-json-xs=2.34
  - r-jsonlite=1.8.2
  - r-readr=2.1.4
  - r-httpuv=1.6.6
  - isa-l=2.30.0
  - xorg-libice=1.0.10
  - krb5=1.19.3
  - r-systemfonts=1.0.4
  - r-segmented=1.5_0
  - readline=8.1.2
  - libblas=3.9.0
  - r-assertive.data.us=0.0_2
  - r-highr=0.9
  - r-assertive.models=0.0_2
  - bioconductor-rhtslib=1.26.0
  - libpng=1.6.38
  - python=3.9.13
  - sed=4.8
  - r-gitcreds=0.1.2
  - perl-extutils-makemaker=7.66
  - r-assertive.numbers=0.0_2
  - r-dplyr=1.0.10
  - r-rmarkdown=2.17
  - mrbayes=3.2.7
  - r-poorman=0.2.6
  - bioconductor-biostrings=2.62.0
  - r-bit=4.0.5
  - xorg-libxt=1.2.1
  - r-rsqlite=2.3.0
  - libedit=3.1.20191231
  - r-ade4=1.7_19
  - r-withr=2.5.0
  - orna
  - xorg-libxrender=0.9.10
  - libdeflate=1.13
  - r-fansi=1.0.3
  - r-vctrs=0.4.2
  - perl-scalar-list-utils=1.62
  - perl-carp=1.38
  - r-dbplyr=2.3.0
  - tk=8.6.12
  - ncurses=6.3
  - r-pkgdown=2.0.6
  - font-ttf-dejavu-sans-mono=2.37
  - spades=3.13.0
  - pango=1.50.11
  - bioconductor-rtracklayer=1.54.0
  - r-textshaping=0.3.6
  - tktable=2.10
  - r-restfulr=0.0.15
  - r-r6=2.5.1
  - xorg-xproto=7.0.31
  - libev=4.33
  - bioconductor-genomeinfodb=1.30.1
  - bioconductor-s4vectors=0.32.4
  - ca-certificates=2022.12.7
  - boost-cpp=1.74.0
  - r-progress=1.2.2
  - openssl=1.1.1t
  - r-generics=0.1.3
  - r-knitr=1.40
  - bioconductor-iranges=2.28.0
  - r-callr=3.7.2
  - c-ares=1.18.1
  - r-sessioninfo=1.2.2
  - r-sourcetools=0.1.7
  - r-fastmap=1.1.0
  - r-base=4.1.3
  - r-stringr=1.4.1
  - r-evaluate=0.17
  - perl-pathtools=3.75
  - r-lifecycle=1.0.3
  - setuptools=65.4.1
  - r-plogr=0.2.0
  - bioconductor-genomicalignments=1.30.0
  - bioconductor-biocparallel=1.28.3
  - perl-compress-raw-zlib=2.105
  - r-jquerylib=0.1.4
  - r-testthat=3.1.5
  - pcre2=10.37
  - r-stringi=1.7.8
  - r-assertive.base=0.0_9
  - r-downlit=0.4.2
  - xorg-libxi=1.7.10
  - libglib=2.74.0
  - openmpi=4.1.4
  - xorg-recordproto=1.14.2
  - bioconductor-zlibbioc=1.40.0
  - r-mime=0.12
  - libxcb=1.13
  - r-clipr=0.8.0
  - r-desc=1.4.2
  - r-codetools=0.2_18
  - r-assertive.strings=0.0_3
  - r-urlchecker=1.0.1
  - perl=5.32.1
  - r-fontawesome=0.3.0
  - r-cachem=1.0.6
  - bwidget=1.9.14
  - perl-exporter=5.72
  - r-yaml=2.3.5
  - r-xml2=1.3.3
  - r-pillar=1.8.1
  - r-gh=1.3.1
  - r-rjson=0.2.21
  - r-later=1.2.0
  - wheel=0.37.1
  - r-assertive.reflection=0.0_5
  - r-mass=7.3_58.1
  - r-zip=2.2.1
  - r-processx=3.7.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-annotationdbi=1.56.2
  - r-credentials=1.3.2
  - libssh2=1.10.0
  - r-htmlwidgets=1.5.4
  - bioconductor-genomicranges=1.46.1
  - font-ttf-source-code-pro=2.038
  - pthread-stubs=0.4
  - fribidi=1.0.10
  - blast=2.12.0
  - bioconductor-rsamtools=2.10.0
  - perl-exporter-tiny=1.002002
  - pandoc=2.19.2
  - pixman=0.40.0
  - r-brio=1.1.3
  - bioconductor-biomart=2.50.0
  - font-ttf-inconsolata=3.000
  - bwa=0.7.17
  - r-askpass=1.1
  - r-crayon=1.5.2
  - expat=2.4.9
  - r-ape=5.7
